### PR TITLE
Added support for arbitrary MySQLdb.connect() kwargs

### LINKED ISSUE #6: Pass other kwargs to MySQLdb.connect() ?
I'd like to use MySQLdb's DictCursor but there doesn't seem to be any way to pass arbitrary keywords to the internal MySQLdb.connect() call - just the connection and charset settings. Is that true?

### PR DESCRIPTION
**Pull request by GordStephen**
This fixes #6 for me - code review is welcome, not sure if it's the best way to go about it?

### CODE REVIEW

**Comment by Regner** [comment]
Is there a reason this never made it in? Was looking at adding something similar to this but if this wasn't accepted would love to know why.

**Comment by cyberdelia** [comment]
Merged in b6e11bd11ece116e05ab009ec5490625e2a672df

**Comment by cyberdelia** [comment]
Thanks, and sorry for the long wait.

**Comment by Regner** [comment]
Hey man, thanks for pulling that. Really appreciate it! :D

**Pull request closed without merging**
